# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import os
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score
from collections import Counter

# ── 1. Load data ──────────────────────────────────────────────
csv_path = 'synthetic_logs.csv'
df = pd.read_csv(csv_path)

print(f"Loaded {len(df)} log messages")
print(f"Columns: {list(df.columns)}")
print(f"Sources: {df['source'].unique()}")
print()

# ── 2. Generate embeddings using SentenceTransformer ──────────
print("Loading SentenceTransformer model...")
model = SentenceTransformer('all-MiniLM-L6-v2')

log_messages = df['log_message'].astype(str).tolist()
print(f"Generating embeddings for {len(log_messages)} log messages...")
embeddings = model.encode(log_messages, show_progress_bar=True, batch_size=32)
print(f"Embedding shape: {embeddings.shape}")
print()

# ── 3. Cluster with DBSCAN ───────────────────────────────────
print("Running DBSCAN clustering...")
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
cluster_labels = dbscan.fit_predict(embeddings)

df['cluster'] = cluster_labels
df.head()

df[df.cluster==1]

pd.set_option('display.max_colwidth', None)
cluster_counts = df['cluster'].value_counts()
large_clusters = cluster_counts[cluster_counts > 10].index
for cluster in large_clusters:
  print(f"Cluster {cluster}:")
  print(df[df['cluster'] == cluster]['log_message'].head(5).to_string(index=False))
  print()

import re

def classify_with_regex(log_messages):
  regex_patterns = {
      r"nova\.osapi_compute\.wsgi\.server.*GET \/v2\/[a-f0-9\-]+\/servers\/detail HTTP\/1\.1.*(status|HTTP status code|RCODE|Return code):?\s*200.*time:\s*[0-9\.]+": "HTTP Status",
      r"nova\.compute\.claims.*(Total memory|memory limit|disk limit|vcpu limit).*": "Resource Usage",
      r"User\s+\w+\s+logged\s+(in|out)\.": "User Action",
      r"Backup (started|ended) at .*": "System Notification",
      r".*(Multiple|multiple).*(login|incorrect).*(attempts|failures).*": "Security Alert",
      r"Backup completed successfully\.": "System Notification",
      r"System updated to version \d+\.\d+\.\d+\.": "System Notification",
      r".*(replication|Replication).*(failed|failure|did not complete).*": "Error",
      r"File .* uploaded successfully by user .*": "System Notification",
      r".*(Denied access|Unauthorized login|blocked|Invalid login attempt).*": "Security Alert",
      r".*(Critical system|malfunction|Failure occurred).*component.*ID .*": "Critical Error",
      r"Disk cleanup completed successfully\.": "System Notification",
      r"System reboot initiated by user .*": "System Notification",
      r"User \d+.*(unauthorized|failed to provide valid API|bypass API|without proper authorization).*": "Security Alert",
      r"Account with ID .* created by .*": "User Action",
      r".*(Email|Mail).*(issue|error|fault|glitch|problem).*": "Error",
      r"nova\.compute\.resource_tracker.*(Final resource view|Total usable vcpus).*": "Resource Usage",
      r".*(security threat|suspicious activity|potential security incident|Anomalous activity).*": "Security Alert",
      r".*(invalid data format|format mismatch|input format|format validation).*": "Data Error",
      r".*(RAID|disk).*(failure|fault|crash|faulty).*": "Hardware Failure",
      r".*SSL certificate.*(failed|invalid|expired|validation).*": "Security Alert",
      r".*(kernel panic|kernel failure|boot process|boot sequence).*(failed|terminated|stopped).*": "Critical Error",
      r"User \d+.*escalated.*admin.*": "Security Alert",
      r".*configuration.*(invalid|corrupted|failure|error).*": "Error",
      r".*(admin privilege escalation|Potential security threat).*": "Security Alert",
      r".*(privilege elevation|elevated admin privileges).*": "Security Alert"
  }
  for pattern, label in regex_patterns.items():
    if re.search(pattern, log_messages, re.IGNORECASE):
      return label
  return None

classify_with_regex("User user1234 logged OUT.")

df['regex_label'] = df['log_message'].apply(classify_with_regex)

df

df[df.regex_label.notnull()]

df_non_regex = df[df.regex_label.isnull()].copy()
df_non_regex.shape

print(df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts() <=5].index.tolist())

df_non_legacy = df_non_regex[df_non_regex['source']!='LegacyCRM']
df_non_legacy.source.unique()

log_messages = df_non_legacy['log_message'].astype(str).tolist()
print(f"Generating embeddings for df_non_legacy {len(log_messages)} log messages...")
filtered_embeddings = model.encode(log_messages, show_progress_bar=True, batch_size=32)
print(f"Embedding shape: {filtered_embeddings.shape}")
print()

X = filtered_embeddings
y = df_non_legacy['target_label']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

import joblib
import os

# Create the directory if it doesn't exist
if not os.path.exists('models'):
    os.makedirs('models')

joblib.dump(clf, 'models/jobclassifier.joblib')

# # First, let's create a dummy .py file to test
# with open('bert_processor.py', 'r') as f:
#     print('bert_processor.py read successfully.')
#     !python bert_processor.py

# with open('llm_processor.py', 'r') as f:
#     print('llm_processor.py read successfully.')
#     !python llm_processor.py



import llm_processor
import bert_processor

def classify(logs):
  Labels = []
  for source, log_msg in logs:
    Label = classify_log(source, log_msg)
    Labels.append(Label)
  return Labels

def classify_log(source, log_message):
  if source == "LegacyCRM":
    # Using the imported module instead of opening the file as text
    return llm_processor.classify_with_llm(log_message)
  else:
    label = classify_with_regex(log_message)
    if label is None:
      return bert_processor.classify_with_bert(log_message)

    return label

def classify_csv(input_file):
    import pandas as pd
    df = pd.read_csv(input_file)

    # Perform classification
    df["target_label"] = classify(list(zip(df["source"], df["log_message"])))

    # Save the modified file
    output_file = "resources/output.csv"
    df.to_csv(output_file, index=False)

    return output_file

if __name__ == '__main__':
    # This function already reads the CSV and runs classification
    output_path = classify_csv("test.csv")

    print(f"Classification complete. Results saved to: {output_path}")

    # Test with the manual list
    logs = [
        ("ModernCRM", "IP 192.168.133.114 blocked due to potential attack"),
        ("BillingSystem", "User 12345 logged in."),
        ("AnalyticsEngine", "File data_6957.csv uploaded successfully by user User265."),
        ("AnalyticsEngine", "Backup completed successfully."),
        ("ModernHR", "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1 RCODE  200 len: 1583 time: 0.1878400"),
        ("ModernHR", "Admin access escalation detected for user 9429"),
        ("LegacyCRM", "Case escalation for ticket ID 7324 failed because the assigned support agent is no longer active."),
        ("LegacyCRM", "Invoice generation process aborted for order ID 8910 due to invalid tax calculation module."),
        ("LegacyCRM", "The 'BulkEmailSender' feature is no longer supported. Use 'EmailCampaignManager' for improved functionality."),
        ("LegacyCRM", " The 'ReportGenerator' module will be retired in version 4.0. Please migrate to the 'AdvancedAnalyticsSuite' by Dec 2025")
    ]

    labels = classify(logs)

    print("\n--- Manual Logs Classification Results ---")
    for log, label in zip(logs, labels):
        print(f"{log[0]} -> {label}")

    # To see the CSV results, we should read the output file
    print("\n--- CSV Logs Classification Results (First 5) ---")
    import pandas as pd
    print(pd.read_csv(output_path)[['source', 'target_label']])

# !pip install groq

